const eventsData = [
  {
    id: 1,
    title: "Bullseye",
    price: "30",
    tag: "CSI",
    college: "CSI",
    image: "/event1.webp",
    desc: "Precision aiming and target shooting competition.",
    phone_no: "+91 7020976545", //9987330273
    prize_pool: "Vouchers",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 2,
    title: "CODM",
    price: "150",
    tag: "CSI",
    college: "CSI",
    image: "/event2.webp",
    desc: "Call of Duty Mobile tournament with exciting prizes.",
    phone_no: "+91 9987330273",
    prize_pool: "₹2000",
    teamSize: { min: 5, max: 5 },
  },
  {
    id: 3,
    title: "Garba Workshop",
    price: "200",
    tag: "CSI",
    college: "CSI",
    image: "/event3.webp",
    desc: "Learn traditional Garba dance steps and rhythms.",
    phone_no: "+91 9987330273",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 4,
    title: "Rink Football",
    price: "400",
    tag: "CSI",
    college: "CSI",
    image: "/event4.webp",
    desc: "Competitive rink football matches and training.",
    phone_no: "+91 9987330273",
    prize_pool: "₹3500",
    teamSize: { min: 7, max: 7 },
  },
  {
    id: 5,
    title: "Tech Hunt",
    price: "100",
    tag: "CSI",
    college: "CSI",
    image: "/event5.webp",
    desc: "A tech-themed scavenger hunt with puzzles and prizes.",
    phone_no: "+91 9987330273",
    prize_pool: "₹1000",
    teamSize: { min: 3, max: 3 },
  },
  {
    id: 6,
    title: "Neon Cricket",
    price: "250",
    tag: "CSI",
    college: "CSI",
    image: "/event6.webp",
    desc: "Night cricket matches with neon lights and music.",
    phone_no: "+91 9987330273",
    prize_pool: "₹2500",
    teamSize: { min: 5, max: 5 },
  },
  {
    id: 7,
    title: "Cricket Auction",
    price: "300",
    tag: "CSI",
    college: "CSI",
    image: "/event7.webp",
    desc: "Auction event for cricket teams and players.",
    phone_no: "+91 9987330273",
    prize_pool: "₹3000",
    teamSize: { min: 5, max: 5 },
  },
  {
    id: 8,
    title: "Escape Room",
    price: "250",
    tag: "ACM",
    college: "ACM",
    image: "/event8.webp",
    desc: "Step into the magical world of Harry Potter! Work with your team, uncover enchanted clues, and race against time to escape from Hogwarts before it's too late!",
    phone_no: "7506734599",
    prize_pool: "₹3000",
    teamSize: { min: 1, max: 4 },
  },
  {
    id: 9,
    title: "Scavenger Hunt",
    price: "200",
    tag: "ACM",
    college: "ACM",
    image: "/event9.webp",
    desc: "A brain-teasing adventure where teams follow clues, solve technical tasks, and navigate challenges to reach the ultimate destination.",
    phone_no: "7506734599",
    prize_pool: "₹3000",
    teamSize: { min: 1, max: 4 },
  },
  {
    id: 10,
    title: "Power Show",
    price: "100",
    tag: "ACM",
    college: "ACM",
    image: "/event10.webp",
    desc: "A power-packed fitness fest featuring group workouts, strength challenges, and competitions like Deadlift and Bench Press.",
    phone_no: "7506734599",
    prize_pool: "₹3000",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 11,
    title: "Valorant",
    price: "400",
    tag: "ACM",
    college: "ACM",
    image: "/event11.webp",
    desc: "Five-player squads battle in 25 thrilling rounds of tactical combat. Only the sharpest strategy and aim will claim victory.",
    phone_no: "7506734599",
    prize_pool: "₹18000",
    teamSize: { min: 5, max: 5 },
  },
  {
    id: 12,
    title: "Dance Workshop",
    price: "150",
    tag: "ACM",
    college: "ACM",
    image: "/event12.webp",
    desc: "A fun-filled freestyle dance workshop for all skill levels. Learn, express, and groove while connecting with fellow dance lovers.",
    phone_no: "7506734599",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 13,
    title: "WWE",
    price: "50",
    tag: "ACM",
    college: "ACM",
    image: "/event13.webp",
    desc: "A knockout-style WWE 2K25 tournament where players choose their superstars, battle it out, and fight for the championship title.",
    phone_no: "7506734599",
    prize_pool: "Vouchers",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 14,
    title: "Project Presentation",
    price: "100",
    tag: "ACM",
    college: "ACM",
    image: "/event14.webp",
    desc: "Students present their Minor and Major projects, highlighting creativity, research, and problem-solving for recognition and awards.",
    phone_no: "7506734599",
    prize_pool: "Certificates",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 15,
    title: "Haunted House",
    price: "100",
    tag: "IETE",
    college: "IETE",
    image: "/event15.webp",
    desc: "Thrilling escape challenge through spooky puzzles and eerie surprises.",
    phone_no: "9082414734",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 4 },
  },
  {
    id: 16,
    title: "Arm Wrestling",
    price: "30",
    tag: "IETE",
    college: "IETE",
    image: "/event16.webp",
    desc: "An intense one-on-one showdown where competitors lock arms, test their power, and battle for dominance in the ultimate strength challenge.",
    phone_no: "9082414734",
    prize_pool: "Vouchers",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 17,
    title: "FIFA PS5",
    price: "150",
    tag: "IETE",
    college: "IETE",
    image: "/event17.webp",
    desc: "A high-energy gaming clash where players showcase their skills, strategies, and passion for football in electrifying matches on the PlayStation 5.",
    phone_no: "9082414734",
    prize_pool: "₹4000",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 18,
    title: "BGMI Classic",
    price: "200",
    tag: "IETE",
    college: "IETE",
    image: "/event18.webp",
    desc: "A battle royale showdown where squads drop in, gear up, and fight to be the last team standing in the classic BGMI mode.",
    phone_no: "9082414734",
    prize_pool: "₹12000",
    teamSize: { min: 4, max: 4 },
  },
  {
    id: 19,
    title: "Squid Game",
    price: "100",
    tag: "IETE",
    college: "IETE",
    image: "/event19.webp",
    desc: "A thrilling set of challenges inspired by the hit series, where participants test their skill, focus, and nerve to outlast the competition and claim victory.",
    phone_no: "9082414734",
    prize_pool: "₹5000",
    teamSize: { min: 4, max: 4 },
  },
  {
    id: 20,
    title: "Gen AI Workshop",
    price: "100",
    tag: "IETE",
    college: "IETE",
    image: "/event20.webp",
    desc: "An interactive workshop introducing students to Generative AI, covering prompt engineering, ethical use, and hands-on tools for text, image, and content creation. Students will explore real-world applications, boosting creativity, productivity, and innovation in the digital era.",
    phone_no: "9082414734",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 21,
    title: "Content Creation Workshop",
    price: "100",
    tag: "IETE",
    college: "IETE",
    image: "/event21.webp",
    desc: "A practical workshop designed to equip students with modern content creation skills like digital storytelling, video editing, designing, and using trending tools. The session also emphasizes strategies for engagement, personal branding, and effective communication, making it highly valuable for aspiring digital creators, explore the digital space.",
    phone_no: "9082414734",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 22,
    title: "Standup Comedy / Car Craze",
    price: "TBD",
    tag: "ASCE",
    college: "ASCE",
    image: "/event22.webp",
    desc: "Either a fun-packed standup comedy show with witty humor, or a thrilling car craze with modified cars, roaring engines, and stunts that excite motorheads and spectators alike.",
    phone_no: "+91 9356216955",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 23,
    title: "Tug of War",
    prices: [
      { teamSize: 6, cost: 300 },
      { teamSize: 8, cost: 400 },
    ],
    tag: "ASCE",
    college: "ASCE",
    image: "/event23.webp",
    desc: "A legacy Zephyr event of pure strength and teamwork where two teams pull the rope past the opponent’s mark, drawing massive participation and audience cheers every year. Price is per team.",
    phone_no: "+91 9356216955",
    prize_pool: "₹5000",
    teamSize: { min: 6, max: 8 },
  },
  {
    id: 24,
    title: "Box Cricket",
    price: "400",
    tag: "ASCE",
    college: "ASCE",
    image: "/event24.webp",
    desc: "Fast-paced cricket in a compact arena with thrilling last-ball finishes and nonstop action, ensuring maximum excitement for both players and spectators.",
    phone_no: "+91 9356216955",
    prize_pool: "₹9000",
    teamSize: { min: 7, max: 7 },
  },
  {
    id: 25,
    title: "BGMI",
    price: "200",
    tag: "ASCE",
    college: "ASCE",
    image: "/event25.webp",
    desc: "A competitive e-sports battle royale where squads face off for survival. Packed with strategy, nail-biting finishes, and massive participation, it’s one of Zephyr’s flagship e-sports events.",
    phone_no: "+91 9356216955",
    prize_pool: "₹12000",
    teamSize: { min: 4, max: 4 },
  },
  {
    id: 26,
    title: "Valorant",
    price: "400",
    tag: "ASCE",
    college: "ASCE",
    image: "/event26.webp",
    desc: "A high-stakes FPS game where two teams compete to plant or defuse the Spike. Intense strategy, precise gameplay, and thrilling fire-fights make it a highlight for gamers and viewers alike.",
    phone_no: "+91 9356216955",
    prize_pool: "₹18000",
    teamSize: { min: 5, max: 5 },
  },
  {
    id: 27,
    title: "Neon Dodgeball",
    price: "60",
    tag: "ASCE",
    college: "ASCE",
    image: "/event27.webp",
    desc: "A glowing twist to dodgeball with neon-lit arenas. Teams dodge, dive, and strike under vibrant lights, making it one of Zephyr’s most electrifying events.",
    phone_no: "+91 9356216955",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 28,
    title: "Technical Event (TBA)",
    price: "Free",
    tag: "ASCE",
    college: "ASCE",
    image: "/event28.webp",
    desc: "A dedicated technical platform for Civil Engineering through workshops, challenges, and industry exposure that enhance practical skills.",
    phone_no: "+91 9356216955",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 29,
    title: "Gel Blaster",
    price: "300",
    tag: "IEEE",
    college: "IEEE",
    image: "/event29.webp",
    desc: "Gel Blaster is a tactical team sport where two squads of 4 participants each face off using gel-bead blasters that fire water-based pellets. ",
    phone_no: "+91 9920660432",
    prize_pool: "Goodies and Vouchers",
    teamSize: { min: 4, max: 4 },
  },
  {
    id: 30,
    title: "Valorant",
    price: "400",
    tag: "IEEE",
    college: "IEEE",
    image: "/event30.webp",
    desc: "This is a team game consisting of five players. Two teams compete against each other trying to plant a bomb in the enemy site while protecting their own site.",
    phone_no: "+91 9920660432",
    prize_pool: "₹18000",
    teamSize: { min: 5, max: 5 },
  },
  {
    id: 31,
    title: "AR Cricket",
    price: "150",
    tag: "IEEE",
    college: "IEEE",
    image: "/event31.webp",
    desc: "AR Cricket is an individual batting challenge designed for solo participants. Each player is given two overs to score the highest runs possible using augmented reality gameplay.",
    phone_no: "+91 9920660432",
    prize_pool: "₹3000",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 32,
    title: "BGMI Classic",
    price: "200",
    tag: "IEEE",
    college: "IEEE",
    image: "/event32.webp",
    desc: "It is a survival action game where multiple squads battle out and survive as a team and the last person standing wins the match.",
    phone_no: "+91 9920660432",
    prize_pool: "₹12000",
    teamSize: { min: 4, max: 4 },
  },
  {
    id: 33,
    title: "Ideathon",
    price: "50",
    tag: "IEEE",
    college: "IEEE",
    image: "/event33.webp",
    desc: "The Ideathon is a team-based event where participants pitch innovative Web3 and AI solutions to real-world challenges. It includes a workshop, an international speaker session, and a pitch competition, with top ideas winning prizes and recognition.",
    phone_no: "+91 9920660432",
    prize_pool: "Prizes in Kind worth ₹30,000",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: 34,
    title: "Art Workshop, (Resin Art)",
    price: "225",
    tag: "IEEE",
    college: "IEEE",
    image: "/event34.webp",
    desc: "Resin Art is a creative workshop where pairs of participants work together to craft unique art pieces.",
    phone_no: "+91 9920660432",
    prize_pool: "Prizes in Kind worth ₹2000",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 35,
    title: "Catch the Baton",
    price: "60",
    tag: "IEEE",
    college: "IEEE",
    image: "/event35.webp",
    desc: "Catch The Baton is a thrilling game that tests your speed, agility, and teamwork! Catch the falling stick and compete with friends to set new records.",
    phone_no: "+91 9920660432",
    prize_pool: "₹1000",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 36,
    title: "Mystery Maze",
    prices: [
      { teamSize: 2, cost: 160 },
      { teamSize: 4, cost: 280 },
    ],
    tag: "ACM-SIGAI",
    college: "ACM-SIGAI",
    image: "/event36.webp",
    desc: "In the Mystery Maze, four participants embark on a thrilling adventure through a complex labyrinth with five challenging levels. Each level presents intricate puzzles and enigmatic clues that must be solved to progress.",
    phone_no: "7045851407",
    prize_pool: "12000",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: 37,
    title: "Takeshi’s Castle",
    prices: [
      { teamSize: 2, cost: 170 },
      { teamSize: 4, cost: 300 },
    ],
    tag: "ACM-SIGAI",
    college: "ACM-SIGAI",
    image: "/event37.webp",
    desc: "This Takeshi’s Castle inspired 3-level game includes Sumo Showdown, Bridge Crossing, and Guard Wall, where contestants dodge sponge balls and restart if hit three times. Full of fun, chaos, and excitement.",
    phone_no: "7045851407",
    prize_pool: "₹10000",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: 38,
    title: "Free Fire",
    prices: [
      { teamSize: 2, cost: 130 },
      { teamSize: 4, cost: 250 },
    ],
    tag: "ACM-SIGAI",
    college: "ACM-SIGAI",
    image: "/event38.webp",
    desc: "The Free Fire event will be conducted as a 4v4 team battle. Teams must work together strategically to outmaneuver and eliminate the opposing team in a best-of-three format. Fast-paced action and teamwork guaranteed.",
    phone_no: "7045851407",
    prize_pool: "₹12000",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: 39,
    title: "Box Cricket",
    price: "400",
    tag: "ACM-SIGAI, S4DS, ASCE",
    college: "ACM-SIGAI, S4DS, ASCE",
    image: "/event39.webp",
    desc: "A high energy adaptation of cricket played in a compact box arena with shorter overs, fast-paced action, and last-ball finishes. Guaranteed adrenaline rush for both players and spectators.",
    phone_no: "7045851407",
    prize_pool: "₹9000",
    teamSize: { min: 5, max: 7 },
  },
  {
    id: 40,
    title: "Bulls Eye",
    price: "30",
    tag: "ACM-SIGAI, CSI",
    college: "ACM-SIGAI, CSI",
    image: "/event40.webp",
    desc: "Bulls Eye is a two-stage event where participants first toss balls into a mini basketball cup, then use a Nerf gun to knock down glasses. Precision, speed, and reflexes decide the winner.",
    phone_no: "7045851407",
    prize_pool: "Coupons",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 41,
    title: "Simulator Mania",
    price: "200",
    tag: "S4DS",
    college: "S4DS",
    image: "/event41.webp",
    desc: "High energy gaming event where players dive into two adrenaline-packed racing experiences: Gran Turismo (GT) and Formula 1(F1).",
    phone_no: "9967056487",
    prize_pool: "₹4000",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 42,
    title: "Neon Bowling",
    price: "120",
    tag: "S4DS",
    college: "S4DS",
    image: "/event42.webp",
    desc: "Regular bowling played under blacklights, where lanes, pins and balls glow in vibrant neon colors.",
    phone_no: "9967056487",
    prize_pool: "₹3000",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 43,
    title: "Box Cricket",
    price: "400",
    tag: "S4DS",
    college: "S4DS",
    image: "/event43.webp",
    desc: "A high-energy, fast paced version of cricket played in a compact arena with shorter overs. This format ensures thrilling, action-packed matches.",
    phone_no: "9967056487",
    prize_pool: "₹9000",
    teamSize: { min: 5, max: 7 },
  },
  {
    id: 44,
    title: "Valorant",
    price: "400",
    tag: "S4DS",
    college: "S4DS",
    image: "/event44.webp",
    desc: "A special team-up where players jump into Riot’s tactical 5v5 shooter, combining strategy, sharp aim, and unique agent abilities.",
    phone_no: "9967056487",
    prize_pool: "₹18000",
    teamSize: { min: 5, max: 5 },
  },
  {
    id: 45,
    title: "Canvasphere Hack",
    price: "50",
    tag: "S4DS",
    college: "S4DS",
    image: "/event45.webp",
    desc: "An online creative challenge where participants use Canva to design bold, eye-catching visuals.",
    phone_no: "9967056487",
    prize_pool: "Goodies",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 46,
    title: "CTF",
    price: "2100",
    tag: "OWASP",
    college: "OWASP",
    image: "/event46.webp",
    desc: "This is a brief description for Event 41.",
    phone_no: "74994 91635",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 47,
    title: "Scribble",
    price: "2100",
    tag: "OWASP",
    college: "OWASP",
    image: "/event47.webp",
    desc: "This is a brief description for Event 41.",
    phone_no: "1234567890",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 48,
    title: "Rocket League",
    price: "2100",
    tag: "OWASP",
    college: "OWASP",
    image: "/event48.webp",
    desc: "This is a brief description for Event 41.",
    phone_no: "1234567890",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 49,
    title: "E football",
    price: "2100",
    tag: "OWASP",
    college: "OWASP",
    image: "/event49.webp",
    desc: "This is a brief description for Event 41.",
    phone_no: "1234567890",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 50,
    title: "Stumble Guys",
    price: "2100",
    tag: "OWASP",
    college: "OWASP",
    image: "/event50.webp",
    desc: "This is a brief description for Event 41.",
    phone_no: "1234567890",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 51,
    title: "Neon Football",
    prices: [
      { teamSize: 1, cost: 70 },
      { teamSize: 2, cost: 120 },
    ],
    prize_pool: "₹2000",
    teamSize: { min: 1, max: 2 },
    tag: "IEI",
    college: "IEI",
    image: "/event51.webp",
    desc: "Glow-in-the-dark football with neon lights, glowing field, ball, and players for a thrilling and immersive game.",
    phone_no: "7304603452",
  },
  {
    id: 52,
    title: "E Arena",
    prices: [
      { teamSize: 1, cost: 120 },
      { teamSize: 2, cost: 200 },
    ],
    prize_pool: "₹5000",
    teamSize: { min: 1, max: 2 },
    tag: "IEI",
    college: "IEI",
    image: "/event52.webp",
    desc: "Gamers compete on PC & PlayStation titles like Mortal Kombat, Tekken, CS2, Fall Guys, and mini-games to climb the leaderboard.",
    phone_no: "7304603452",
  },
  {
    id: 53,
    title: "Seminar On AIot",
    price: "100",
    prize_pool: "₹1000",
    tag: "IEI",
    college: "IEI",
    image: "/event53.webp",
    desc: "Discover how AI-driven IoT transforms industries—smart homes, healthcare, transport, & more—with real-world insights and future trends.",
    phone_no: "7304603452",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 54,
    title: "Space Blitz(Ar Vr)",
    price: "120",
    teamSize: { min: 1, max: 2 },
    prize_pool: "₹1000",
    tag: "IEI",
    college: "IEI",
    image: "/event54.webp",
    desc: "Test reflexes and aim—shoot targets, score points, climb ranks, and win prizes in a fast-paced contest.",
    phone_no: "7304603452",
  },
  {
    id: 55,
    title: "Minute to Win It",
    prices: [
      { teamSize: 1, cost: 50 },
      { teamSize: 2, cost: 100 },
    ],
    teamSize: { min: 1, max: 2 },
    prize_pool: "₹1000",
    tag: "IEI",
    college: "IEI",
    image: "/event55.webp",
    desc: "Two-player teams race through rapid 1‑minute games, earning points through speed, skill, and teamwork.",
    phone_no: "7304603452",
  },
  {
    id: 56,
    title: "CAD Competition",
    price: "200",
    tag: "TRS",
    college: "TRS",
    image:
      "https://github.com/ap27killerclown/ap27killerclown/blob/main/823550ab-2289-4d64-83f7-33116aa188c8.jpg?raw=true",
    desc: "CAD Competition is a design event where participants use Computer-Aided Design software to model given components or problem statements within a set time. Players apply creativity and precision to create 2D sketches or 3D models. Designs are judged on accuracy, innovation, and efficiency, making it a true test of engineering visualization skills. ",
    phone_no: "+91 98214 30779",
    prize_pool: "₹5000",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 57,
    title: "3D Printing Workshop",
    price: "200",
    tag: "TRS",
    college: "TRS",
    image:
      "https://github.com/ap27killerclown/ap27killerclown/blob/main/c925c610-24ce-4e68-ae2a-ef9780f48a54.jpg?raw=true",
    desc: "3D Printing Workshop is a hands-on learning session where participants explore the basics of additive manufacturing. Attendees learn how digital 3D models are designed and then transformed into physical objects using a 3D printer. The workshop focuses on understanding the technology, materials, and applications of 3D printing in real-world engineering and innovation.  ",
    phone_no: "+91 98214 30779",
    prize_pool: "Certificate",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 58,
    title: "BGMI (TDM)",
    price: "200",
    tag: "TRS",
    college: "TRS",
    image:
      "https://github.com/ap27killerclown/ap27killerclown/blob/main/dc5faca5-eb7f-4b45-90c3-bbe4372de8e9.jpg?raw=true",
    desc: "BGMI TDM (Team Deathmatch) is a fast-paced multiplayer battle mode in Battlegrounds Mobile India. Two teams of players compete in a small arena, where the objective is to eliminate opponents and reach the target kill count before the other team. Matches are quick, intense, and focus on reflexes, teamwork, and weapon mastery. ",
    phone_no: "+91 98214 30779",
    prize_pool: "₹8000",
    teamSize: { min: 4, max: 4 },
  },
  {
    id: 59,
    title: "Glow Carrom",
    price: "150",
    tag: "TRS",
    college: "TRS",
    image:
      "https://github.com/ap27killerclown/ap27killerclown/blob/main/f7d9eb7d-69a3-46d0-8730-ba5e71e673f1.jpg?raw=true",
    desc: "Glow Carrom is a fun twist on the classic board game, played under UV or neon lighting with glow-in-the-dark coins and a board. Players use the striker to pocket glowing coins, aiming to score points just like in traditional carrom, but with an exciting visual effect that makes the game more engaging and lively. ",
    phone_no: "+91 98214 30779",
    prize_pool: "₹3500",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 60,
    title: "Dart Football",
    price: "40",
    tag: "TRS",
    college: "TRS",
    image:
      "https://github.com/ap27killerclown/ap27killerclown/blob/main/519b00e1-8cae-4c4e-9eca-3ff7d6206fb6.jpg?raw=true",
    desc: "Football Darts is a fun, hybrid game that combines elements of football (soccer) and darts. In this game, a giant inflatable or poster dartboard is mounted vertically on a wall or stand. Players aim to kick a football at the dartboard, trying to hit specific sections to score points, just like in traditional darts. The closer the ball lands to the bullseye, the higher the score. The game is typically played in rounds ",
    phone_no: "+91 98214 30779",
    prize_pool: "Prizes in Kind",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 61,
    title: "Photo Booth",
    price: "100",
    tag: "BBA",
    college: "BBA",
    image:
      "https://raw.githubusercontent.com/ap27killerclown/ap27killerclown/refs/heads/main/491a4fbd-cad9-4941-9f1b-755522c95e25.png",
    desc: "A vintage-themed photo booth designed to create a nostalgic atmosphere for attendees. The setup will include retro backdrops, fairy lights, and an array of antique props such as gramophones, hats, mustaches, old cameras, and funky vintage frames, providing the perfect opportunity to capture memorable and stylish photographs.",
    phone_no: "+91 99694 61707",
    prize_pool: "Not Applicable",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 62,
    title: "Anomaly",
    price: "60",
    tag: "ACM-SIGAI, BCA",
    college: "ACM-SIGAI, BCA",
    image: "/event62.webp",
    desc: "Anomaly is a retro terminal-style puzzle adventure where you play as a Debugger guided by Glitch. Solve paradoxes, decode strange patterns, and repair corrupted data to defeat the system anomaly.",
    phone_no: "7045851407",
    prize_pool: "₹8000",
    teamSize: { min: 1, max: 1 },
  },
  {
    id: 63,
    title: "Murderer Among Us",
    price: "60",
    tag: "BCA",
    college: "BCA",
    image: "/event63.webp",
    desc: "Step into a classroom turned crime scene in this thrilling mystery game! Each round, every player receives unique scripts with secrets and clues about a shocking campus murder. But beware — one of you is the hidden murderer! Can you solve the case before time runs out? ",
    phone_no: "8452801821",
    prize_pool: "Upto ₹2000",
    teamSize: { min: 1, max: 1 },
  },
];

export default eventsData;
