// eventsData updated with the specified committee names in the 'tag' and 'committee' fields.

const eventsData = [
  {
    id: 1,
    title: "Event 1",
    price: "₹100",
    tag: "ACM",
    committee: "ACM",
    image: "/event1.jpg",
    desc: "This is a brief description for Event 1.",
    phone_no: "1234567890",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: 2,
    title: "Event 2",
    price: "₹200",
    tag: "CSI",
    committee: "CSI",
    image: "/event2.jpg",
    desc: "This is a brief description for Event 2.",
    phone_no: "1234567890",
  },
  {
    id: 3,
    title: "Event 3",
    price: "₹300",
    tag: "IEEE",
    committee: "IEEE",
    image: "/event3.jpg",
    desc: "This is a brief description for Event 3.",
    phone_no: "1234567890",
    teamSize: { min: 1, max: 2 },
  },
  {
    id: 4,
    title: "Event 4",
    price: "₹400",
    tag: "IETE",
    committee: "IETE",
    image: "/event4.jpg",
    desc: "This is a brief description for Event 4.",
    phone_no: "1234567890",
    teamSize: { min: 3, max: 5 },
  },
  {
    id: 5,
    title: "Event 5",
    price: "₹500",
    tag: "SIGAI",
    committee: "SIGAI",
    image: "/event5.jpg",
    desc: "This is a brief description for Event 5.",
    phone_no: "1234567890",
  },
  {
    id: 6,
    title: "Event 6",
    price: "₹600",
    tag: "IEI",
    committee: "IEI",
    image: "/event6.jpg",
    desc: "This is a brief description for Event 6.",
    phone_no: "1234567890",
    teamSize: { min: 2, max: 3 },
  },
  {
    id: 7,
    title: "Event 7",
    price: "₹700",
    tag: "ASCE",
    committee: "ASCE",
    image: "/event7.jpg",
    desc: "This is a brief description for Event 7.",
    phone_no: "1234567890",
  },
  {
    id: 8,
    title: "Event 8",
    price: "₹800",
    tag: "TRS",
    committee: "TRS",
    image: "/event8.jpg",
    desc: "This is a brief description for Event 8.",
    phone_no: "1234567890",
  },
  {
    id: 9,
    title: "Event 9",
    price: "₹900",
    tag: "OWASP",
    committee: "OWASP",
    image: "/event9.jpg",
    desc: "This is a brief description for Event 9.",
    phone_no: "1234567890",
    teamSize: { min: 1, max: 2 },
  },
  {
    id: 10,
    title: "Event 10",
    price: "₹1000",
    tag: "ACM",
    committee: "ACM",
    image: "/event10.jpg",
    desc: "This is a brief description for Event 10.",
    phone_no: "1234567890",
  },
  {
    id: 11,
    title: "Event 11",
    price: "₹1100",
    tag: "CSI",
    committee: "CSI",
    image: "/event11.jpg",
    desc: "This is a brief description for Event 11.",
    phone_no: "1234567890",
    teamSize: { min: 3, max: 5 },
  },
  {
    id: 12,
    title: "Event 12",
    price: "₹1200",
    tag: "IEEE",
    committee: "IEEE",
    image: "/event12.jpg",
    desc: "This is a brief description for Event 12.",
    phone_no: "1234567890",
  },
  {
    id: 13,
    title: "Event 13",
    price: "₹1300",
    tag: "IETE",
    committee: "IETE",
    image: "/event13.jpg",
    desc: "This is a brief description for Event 13.",
    phone_no: "1234567890",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: 14,
    title: "Event 14",
    price: "₹1400",
    tag: "SIGAI",
    committee: "SIGAI",
    image: "/event14.jpg",
    desc: "This is a brief description for Event 14.",
    phone_no: "1234567890",
  },
  {
    id: 15,
    title: "Event 15",
    price: "₹1500",
    tag: "IEI",
    committee: "IEI",
    image: "/event15.jpg",
    desc: "This is a brief description for Event 15.",
    phone_no: "1234567890",
    teamSize: { min: 1, max: 2 },
  },
  {
    id: 16,
    title: "Event 16",
    price: "₹1600",
    tag: "ASCE",
    committee: "ASCE",
    image: "/event16.jpg",
    desc: "This is a brief description for Event 16.",
    phone_no: "1234567890",
  },
  {
    id: 17,
    title: "Event 17",
    price: "₹1700",
    tag: "TRS",
    committee: "TRS",
    image: "/event17.jpg",
    desc: "This is a brief description for Event 17.",
    phone_no: "1234567890",
  },
  {
    id: 18,
    title: "Event 18",
    price: "₹1800",
    tag: "OWASP",
    committee: "OWASP",
    image: "/event18.jpg",
    desc: "This is a brief description for Event 18.",
    phone_no: "1234567890",
    teamSize: { min: 3, max: 5 },
  },
  {
    id: 19,
    title: "Event 19",
    price: "₹1900",
    tag: "ACM",
    committee: "ACM",
    image: "/event19.jpg",
    desc: "This is a brief description for Event 19.",
    phone_no: "1234567890",
  },
  {
    id: 20,
    title: "Event 20",
    price: "₹2000",
    tag: "CSI",
    committee: "CSI",
    image: "/event20.jpg",
    desc: "This is a brief description for Event 20.",
    phone_no: "1234567890",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: 21,
    title: "Event 21",
    price: "₹2100",
    tag: "IEEE",
    committee: "IEEE",
    image: "/event21.jpg",
    desc: "This is a brief description for Event 21.",
    phone_no: "1234567890",
  },
  {
    id: 22,
    title: "Event 22",
    price: "₹2200",
    tag: "IETE",
    committee: "IETE",
    image: "/event22.jpg",
    desc: "This is a brief description for Event 22.",
    phone_no: "1234567890",
  },
  {
    id: 23,
    title: "Event 23",
    price: "₹2300",
    tag: "SIGAI",
    committee: "SIGAI",
    image: "/event23.jpg",
    desc: "This is a brief description for Event 23.",
    phone_no: "1234567890",
    teamSize: { min: 1, max: 2 },
  },
  {
    id: 24,
    title: "Event 24",
    price: "₹2400",
    tag: "IEI",
    committee: "IEI",
    image: "/event24.jpg",
    desc: "This is a brief description for Event 24.",
  },
  {
    id: 25,
    title: "Event 25",
    price: "₹2500",
    tag: "ASCE",
    committee: "ASCE",
    image: "/event25.jpg",
    desc: "This is a brief description for Event 25.",
    teamSize: { min: 2, max: 3 },
  },
  {
    id: 26,
    title: "Event 26",
    price: "₹2600",
    tag: "TRS",
    committee: "TRS",
    image: "/event26.jpg",
    desc: "This is a brief description for Event 26.",
  },
  {
    id: 27,
    title: "Event 27",
    price: "₹2700",
    tag: "OWASP",
    committee: "OWASP",
    image: "/event27.jpg",
    desc: "This is a brief description for Event 27.",
  },
  {
    id: 28,
    title: "Event 28",
    price: "₹2800",
    tag: "ACM",
    committee: "ACM",
    image: "/event28.jpg",
    desc: "This is a brief description for Event 28.",
    teamSize: { min: 3, max: 5 },
  },
  {
    id: 29,
    title: "Event 29",
    price: "₹2900",
    tag: "CSI",
    committee: "CSI",
    image: "/event29.jpg",
    desc: "This is a brief description for Event 29.",
  },
  {
    id: 30,
    title: "Event 30",
    price: "₹900",
    tag: "IEEE",
    committee: "IEEE",
    image: "/event30.jpg",
    desc: "This is a brief description for Event 30.",
  },
  {
    id: 31,
    title: "Event 31",
    price: "₹1000",
    tag: "IETE",
    committee: "IETE",
    image: "/event31.jpg",
    desc: "This is a brief description for Event 31.",
  },
  {
    id: 32,
    title: "Event 32",
    price: "₹1200",
    tag: "SIGAI",
    committee: "SIGAI",
    image: "/event32.jpg",
    desc: "This is a brief description for Event 32.",
    teamSize: { min: 2, max: 4 },
  },
  {
    id: 33,
    title: "Event 33",
    price: "₹1300",
    tag: "IEI",
    committee: "IEI",
    image: "/event33.jpg",
    desc: "This is a brief description for Event 33.",
  },
  {
    id: 34,
    title: "Event 34",
    price: "₹1400",
    tag: "ASCE",
    committee: "ASCE",
    image: "/event34.jpg",
    desc: "This is a brief description for Event 34.",
  },
  {
    id: 35,
    title: "Event 35",
    price: "₹1500",
    tag: "TRS",
    committee: "TRS",
    image: "/event35.jpg",
    desc: "This is a brief description for Event 35.",
  },
  {
    id: 36,
    title: "Event 36",
    price: "₹1600",
    tag: "OWASP",
    committee: "OWASP",
    image: "/event36.jpg",
    desc: "This is a brief description for Event 36.",
  },
  {
    id: 37,
    title: "Event 37",
    price: "₹1700",
    tag: "ACM",
    committee: "ACM",
    image: "/event37.jpg",
    desc: "This is a brief description for Event 37.",
  },
  {
    id: 38,
    title: "Event 38",
    price: "₹1800",
    tag: "CSI",
    committee: "CSI",
    image: "/event38.jpg",
    desc: "This is a brief description for Event 38.",
  },
  {
    id: 39,
    title: "Event 39",
    price: "₹1900",
    tag: "IEEE",
    committee: "IEEE",
    image: "/event39.jpg",
    desc: "This is a brief description for Event 39.",
  },
  {
    id: 40,
    title: "Event 40",
    price: "₹2000",
    tag: "IETE",
    committee: "IETE",
    image: "/event40.jpg",
    desc: "This is a brief description for Event 40.",
    teamSize: { min: 1, max: 2 },
  },
  {
    id: 41,
    title: "Event 41",
    price: "₹2100",
    tag: "SIGAI",
    committee: "SIGAI",
    image: "/event41.jpg",
    desc: "This is a brief description for Event 41.",
    phone_no: "1234567890",
  },
  {
    id: 42,
    title: "Event 42",
    price: "₹2200",
    tag: "IEI",
    committee: "IEI",
    image: "/event42.jpg",
    desc: "This is a brief description for Event 42.",
    phone_no: "1234567890",
  },
  {
    id: 43,
    title: "Event 43",
    price: "₹2300",
    tag: "ASCE",
    committee: "ASCE",
    image: "/event43.jpg",
    desc: "This is a brief description for Event 43.",
    phone_no: "1234567890",
    teamSize: { min: 3, max: 5 },
  },
];

export default eventsData;
